FROM mcr.microsoft.com/windows/servercore:1803 as installer

SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop';$ProgressPreference='silentlyContinue';"]

RUN Invoke-WebRequest -OutFile nodejs.zip -UseBasicParsing "https://nodejs.org/dist/v12.4.0/node-v12.4.0-win-x64.zip" 
CMD ["Expand-Archive", "nodejs.zip", "-DestinationPath C:\"] 
RUN Rename-Item "C:\\node-v12.4.0-win-x64" c:\nodejs

FROM mcr.microsoft.com/windows/nanoserver:1803

WORKDIR C:\nodejs
COPY --from=installer C:\nodejs\ .
RUN SETX PATH C:\nodejs
RUN npm config set registry https://registry.npmjs.org/

WORKDIR /app

# install and cache app dependencies
COPY frontend/src/package.json /app/src/WebSpa/package.json

WORKDIR /app/src/WebSpa
RUN npm install 
# add app
COPY . /app
EXPOSE 3000
# start app
CMD cd /app/src/WebSpa && ["npm","start"]
